version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app #maps volume on our system with the volume on container and updates it accordingly
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"